Processed some 3rd party feedback

diff --git a/secure-signal-download b/secure-signal-download
--- a/secure-signal-download
+++ b/secure-signal-download
@@ -1,36 +1,35 @@
 #!/bin/bash
 
-declare -r repo_url="https://updates.signal.org/desktop/apt"
-declare -r repo_dist="xenial"
-declare -r packages_url="main/binary-amd64/Packages"
+repo_url="https://updates.signal.org/desktop/apt"
+repo_dist="xenial"
+packages_url="main/binary-amd64/Packages"
 
 
 # As of Wget 1.10, the default is to verify the server's certificate against the recognized certificate authorities
-if ! wget --quiet --output-document keys.asc "$repo_url"/keys.asc; then
-  echo "Could not download the Signal public key"
+if ! command wget --quiet --output-document keys.asc "$repo_url"/keys.asc 2>/dev/null; then
+  printf "Could not download the Signal public key\n"
 fi
 
 
-if ! wget --quiet --output-document InRelease "$repo_url"/dists/"$repo_dist"/InRelease; then
-  echo "Could not download the InRelease file"
+if ! command wget --quiet --output-document InRelease "$repo_url"/dists/"$repo_dist"/InRelease 2>/dev/null; then
+  printf "Could not download the InRelease file\n"
 fi
 
 
-if ! wget --quiet --output-document Packages "$repo_url/dists/$repo_dist/$packages_url"; then
-  echo "Could not download the Packages file"
+if ! command wget --quiet --output-document Packages "$repo_url/dists/$repo_dist/$packages_url" 2>/dev/null; then
+  printf "Could not download the Packages file\n"
 fi
 
 
 # Import the downloaded Signal GPG key
-if ! gpg --quiet --import keys.asc; then
-  echo "Could not import Signal public key into GPG"
+if ! command gpg --quiet --import keys.asc 2>/dev/null; then
+  printf "Could not import Signal public key into GPG\n"
 fi
 
 
 # Verify the downloaded InRelease file with the Signal public GPG key
-if ! gpg --quiet --verify InRelease 2>/dev/null; then
-  echo "The GPG signature of the InRelease file is invalid!"
-  exit 1
+if ! command gpg --quiet --verify InRelease 2>/dev/null 2>/dev/null; then
+  printf "The GPG signature of the InRelease file is invalid!\n"
 fi
 
 
@@ -41,7 +40,7 @@ read -r packages_file_hash _ < <(sha256sum Packages)
 while read -r packages_meta_hash _ packages_meta_file; do
   # Verify the hash of the downloaded Packages file with the hash from the verified (InRelease) metadata
   if [[ "$packages_file_hash" == "$packages_meta_hash" && "$packages_meta_file" == "$packages_url" ]]; then
-    declare -r packages_file_verified="yes"
+    packages_file_verified="yes"
     break
   fi
 done < InRelease
@@ -52,8 +51,8 @@ if [[ "$packages_file_verified" == "yes" ]]; then
   while IFS=': ' read -r key value; do
     # When the first 'Filename' line is found in the Packages file, get the signal-desktop.deb URL to download the latest version
     if [[ "$key" == "Filename" ]]; then
-      if ! wget --quiet --output-document signal-desktop.deb "$repo_url/$value"; then
-        echo "Could not download signal-desktop.deb from Packages metadata"
+      if ! command wget --quiet --output-document signal-desktop.deb "$repo_url/$value" 2>/dev/null; then
+        printf "Could not download signal-desktop.deb from Packages metadata\n"
       fi
     fi
   
@@ -64,9 +63,11 @@ if [[ "$packages_file_verified" == "yes" ]]; then
   
       # Verify the hash of the downloaded signal-desktop.deb file with the hash from the verfied (Packages) metadata
       if [[ "$signal_file_hash" == "$value" ]]; then
-        echo "The signal-desktop.deb file is verified as: $signal_file_hash"
+        printf "The signal-desktop.deb file is verified as: %s\n" "$signal_file_hash"
       fi
       break
     fi
   done < Packages
 fi
+
+command rm --force keys.asc InRelease Packages
