improved error output handling

diff --git a/secure-signal-download b/secure-signal-download
--- a/secure-signal-download
+++ b/secure-signal-download
@@ -1,5 +1,8 @@
 #!/bin/bash
 
+error() { local r=$1; shift; printf 'ERROR %s\n' "$*" >&2; exit "$r"; }
+info() { printf 'INFO %s\n' "$*"; }
+
 repo_url="https://updates.signal.org/desktop/apt"
 repo_dist="xenial"
 packages_url="main/binary-amd64/Packages"
@@ -7,29 +10,29 @@ packages_url="main/binary-amd64/Packages"
 
 # As of Wget 1.10, the default is to verify the server's certificate against the recognized certificate authorities
 if ! command wget --quiet --output-document keys.asc "$repo_url"/keys.asc 2>/dev/null; then
-  printf "Could not download the Signal public key\n"
+  error "Could not download the Signal public key"
 fi
 
 
 if ! command wget --quiet --output-document InRelease "$repo_url"/dists/"$repo_dist"/InRelease 2>/dev/null; then
-  printf "Could not download the InRelease file\n"
+  error "Could not download the InRelease file"
 fi
 
 
 if ! command wget --quiet --output-document Packages "$repo_url/dists/$repo_dist/$packages_url" 2>/dev/null; then
-  printf "Could not download the Packages file\n"
+  error "Could not download the Packages file"
 fi
 
 
 # Import the downloaded Signal GPG key
 if ! command gpg --quiet --import keys.asc 2>/dev/null; then
-  printf "Could not import Signal public key into GPG\n"
+  error "Could not import Signal public key into GPG"
 fi
 
 
 # Verify the downloaded InRelease file with the Signal public GPG key
 if ! command gpg --quiet --verify InRelease 2>/dev/null 2>/dev/null; then
-  printf "The GPG signature of the InRelease file is invalid!\n"
+  error "The GPG signature of the InRelease file is invalid!"
 fi
 
 
@@ -52,7 +55,7 @@ if [[ "$packages_file_verified" == "yes" ]]; then
     # When the first 'Filename' line is found in the Packages file, get the signal-desktop.deb URL to download the latest version
     if [[ "$key" == "Filename" ]]; then
       if ! command wget --quiet --output-document signal-desktop.deb "$repo_url/$value" 2>/dev/null; then
-        printf "Could not download signal-desktop.deb from Packages metadata\n"
+        error "Could not download signal-desktop.deb from Packages metadata"
       fi
     fi
   
@@ -63,7 +66,7 @@ if [[ "$packages_file_verified" == "yes" ]]; then
   
       # Verify the hash of the downloaded signal-desktop.deb file with the hash from the verfied (Packages) metadata
       if [[ "$signal_file_hash" == "$value" ]]; then
-        printf "The signal-desktop.deb file is verified as: %s\n" "$signal_file_hash"
+        info "The signal-desktop.deb file is verified as:" "$signal_file_hash"
       fi
       break
     fi
